### ISSUE TITLE
The main src folder must be named `com/scate` instead of `com/example`

### ISSUE THREAD

**Issue by resultanyildizi** [scate-io/scatesdk_flutter#1]
```
The plugin `scatesdk_flutter` doesn't have a main class defined in
.../scatesdk_flutter-0.2.0/android/src/main/java/com/scate/scatesdk_flutter/ScatesdkFlutterPlugin.java or
.../hosted/pub.dev/scatesdk_flutter-0.2.0/android/src/main/kotlin/com/scate/scatesdk_flutter/ScatesdkFlutterPlugin.kt
```

The folder and package name must be the same.

![SCR-20240729-phat](https://github.com/user-attachments/assets/0a412feb-0cae-4b39-aa38-4c39991467db)

![SCR-20240729-pgxw](https://github.com/user-attachments/assets/2db567d7-988b-4105-8468-2acc0853edca)

**Comment by scateio** [comment]
Thanks for reporting. It's fixed now. You can update to 0.2.1 version to have it working..
